In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
import numpy as np

# Build a simple RNN model for binary classification from sequence data

# Create a sequential model
model = Sequential()

# Add a SimpleRNN layer
# - 3 units (RNN cells)
# - Input shape: 4 timesteps, each with 5 features
model.add(SimpleRNN(3, input_shape=(4, 5), activation='tanh'))

# Add an output layer with 1 neuron and sigmoid activation (binary classification)
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()

# Get all trainable weights and their names
weights = model.weights

# Iterate and print each weight/bias with its name, shape, and values
print("\n===== DETAILED WEIGHTS & BIASES =====")
for i, w in enumerate(weights):
    weight_name = w.name
    weight_value = model.get_weights()[i]
    print(f"\n[{i}] {weight_name}")
    print(f"Shape: {weight_value.shape}")
    print("Values:\n", weight_value)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)


===== DETAILED WEIGHTS & BIASES =====

[0] kernel
Shape: (5, 3)
Values:
 [[ 0.64978164  0.10931486  0.4198826 ]
 [-0.33345097  0.8464332   0.70021445]
 [ 0.4788621   0.24449831  0.72215337]
 [ 0.80185264 -0.77968395 -0.80823797]
 [ 0.7393066  -0.13088489  0.57299465]]

[1] recurrent_kernel
Shape: (3, 3)
Values:
 [[-0.73666966  0.5871845   0.3354583 ]
 [ 0.33236286  0.74637973 -0.57658684]
 [ 0.58894205  0.31326014  0.7449935 ]]

[2] bias
Shape: (3,)
Values:
 [0. 0. 0.]

[3] kernel
Shape: (3, 1)
Values:
 [[ 0.07727563]
 [-0.23624241]
 [-0.27726054]]

[4] bias
Shape: (1,)
Values:
 [0.]


In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Build a simple ANN for binary classification

# Create a sequential model
model_ann = Sequential()

# Input layer and first hidden layer
# Input has 10 features, and we use 8 neurons in the hidden layer with ReLU activation
model_ann.add(Dense(8, input_dim=10, activation='relu'))

# Second hidden layer with 4 neurons
model_ann.add(Dense(4, activation='relu'))

# Output layer with 1 neuron (for binary classification) and sigmoid activation
model_ann.add(Dense(1, activation='sigmoid'))

# Compile the model using binary crossentropy loss and Adam optimizer
model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print model summary
model_ann.summary()

# Print weights and biases
print("\n===== ANN Weights & Biases =====")
for i, w in enumerate(model_ann.weights):
    print(f"\n[{i}] {w.name}")
    print(f"Shape: {w.shape}")
    print("Values:\n", model_ann.get_weights()[i])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)


===== ANN Weights & Biases =====

[0] kernel
Shape: (10, 8)
Values:
 [[ 0.36452526 -0.34380546 -0.3827793  -0.16437185 -0.08455202 -0.548106
  -0.30280116 -0.5589115 ]
 [-0.55087817  0.15405267 -0.53007305  0.315288   -0.33390918 -0.14504659
  -0.5190651  -0.10248476]
 [ 0.5535724   0.0369845   0.39632195 -0.22236821  0.00165606  0.45754075
   0.44539416  0.26554477]
 [ 0.38028288  0.10219777  0.19711655  0.42203087  0.34858745  0.26028544
   0.52408767  0.27285725]
 [ 0.39188576  0.07100302 -0.41222823 -0.02960253 -0.02848095 -0.05577123
   0.06776285 -0.4912304 ]
 [-0.29889655  0.2748518  -0.41151917  0.3716454  -0.3145567   0.11488688
   0.08508813  0.48993874]
 [-0.42033285 -0.34880868 -0.30506855 -0.33793247  0.24615264  0.19241452
  -0.40187603 -0.23702487]
 [-0.09529993  0.2943315   0.19059575 -0.35071278  0.10176319 -0.3953588
  -0.2848809  -0.49961555]
 [ 0.16807204 -0.08857265  0.25529367  0.37386942 -0.31048787 -0.00946188
  -0.4771937   0.19601369]
 [-0.4069909  -0.4166144

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import numpy as np

# Build a simple CNN for image classification (e.g., MNIST-like 28×28 grayscale images)

# Create a sequential model
model_cnn = Sequential()

# Add a convolutional layer:
# - 32 filters
# - 3x3 kernel size
# - Input shape: 28x28 image with 1 channel (grayscale)
model_cnn.add(Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))

# Add a max pooling layer (downsamples 2x2)
model_cnn.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten the 2D feature maps into 1D
model_cnn.add(Flatten())

# Add a fully connected hidden layer with 64 neurons
model_cnn.add(Dense(64, activation='relu'))

# Add an output layer for 10-class classification (softmax)
model_cnn.add(Dense(10, activation='softmax'))

# Compile the model using categorical crossentropy (for multiclass classification)
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Print model summary
model_cnn.summary()

# Print weights and biases
print("\n===== CNN Weights & Biases =====")
for i, w in enumerate(model_cnn.weights):
    print(f"\n[{i}] {w.name}")
    print(f"Shape: {w.shape}")
    print("Values:\n", model_cnn.get_weights()[i])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │       346,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 347,146 (1.32 MB)

 Trainable params: 347,146 (1.32 MB)

 Non-trainable params: 0 (0.00 B)


===== CNN Weights & Biases =====

[0] kernel
Shape: (3, 3, 1, 32)
Values:
 [[[[ 0.07406461  0.03865387  0.00391972  0.01206955 -0.04089389
     0.01362865  0.01158558 -0.11142911 -0.06835311  0.01748186
    -0.06074157 -0.13766629 -0.06290514  0.02637513 -0.0045646
     0.04338001 -0.00935046  0.03632134 -0.06405718  0.09218241
     0.13796742  0.03444038  0.0492727  -0.09084444 -0.09682111
     0.05911142  0.07836187  0.01865989 -0.06424095 -0.03165834
    -0.12263182  0.03647539]]

  [[-0.13211587 -0.09537542  0.12499093  0.09414168 -0.11700249
     0.13478114  0.08133878  0.00601205 -0.08649616 -0.05753596
    -0.06407388 -0.14151745  0.0419549  -0.09668028  0.09173602
    -0.02008252 -0.06394941  0.08823508  0.01257403  0.11385755
     0.13267581 -0.013824   -0.11455006  0.0178574  -0.11712486
     0.10769916  0.04793802  0.12637074 -0.01106462 -0.09933976
     0.14090855  0.00659892]]

  [[-0.0623088   0.06065828  0.06739962 -0.13929538  0.03666224
     0.07925981 -0.05480912 -0.